[project]
name = "monthly-group-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Danny Hazley", email = "54882850+dannyhazley@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datetime>=6.0",
    "dotenv>=0.9.9",
    "markdown>=3.10.3",
    "pydantic>=2.13.4",
    "pymongo[srv]==3.12",
    "typing-extensions>=4.16.0",
]

[project.scripts]
monthly-group-blog = "monthly_group_blog:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
